name: Build Judge App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: "Tests and APKs"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Checkstyle
        run: ./gradlew checkstyle --no-daemon

      - name: PMD
        run: ./gradlew pmd --no-daemon

      # The task is non-blocking and can fail for now.
      - name: SpotBugs
        run: ./gradlew spotbugsRelease --no-daemon || true

      - name: Build all build type
        run: ./gradlew :app:assemble -PminifyWithR8=false

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: '**/build/outputs/apk/**/*.apk'

      - name: Upload static analysis reports
        uses: actions/upload-artifact@v4
        with:
          name: Static Analysis Reports
          path: |
            app/build/reports/**