name: Build Judge App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: "Tests and APKs"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Checkstyle
        run: ./gradlew checkstyle --no-daemon

      - name: PMD
        run: ./gradlew pmd --no-daemon

      - name: SpotBugs
        run: ./gradlew spotbugsMain --no-daemon

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon
